# Assignment 2
**You need to work with numpy library. Write code and perform computations in the cells below. There are nine questions.**

In [3]:
import numpy as np

__1. Create a one-dimensional array with 12 elements containing numbers from 5 to 16. Display the product of all elements and their median value.__

In [17]:
arr = np.arange(5,17)
arr

np.median(arr)

10.5

__2. Create an array of numbers from 5 to 55 with a step of 7. Display the elements of the array that are greater than 25 and less than 50.__

In [23]:
arr1 = np.arange(5,56,7)

filtered_array = arr1[(arr1 > 25) & (arr1 < 50)]

print(filtered_array)

[26 33 40 47]


__3. Create a 6x6 matrix with column values ranging from 2 to 7.__

In [93]:
matrix = np.tile(np.arange(2,8),(6,1))

print(matrix)

[[2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]]


__4. Create a random vector of size 12 and find its minimum and maximum values.__

In [69]:
vector = np.random.rand(4,3)

min_of_array = np.min(vector)
max_of_array = np.max(vector)
print(vector,'\n')

print(min_of_array,'\n')
print(max_of_array,'\n')

[[0.1459115  0.28367398 0.85249402]
 [0.51298414 0.07540738 0.39482981]
 [0.39364687 0.2957596  0.19043554]
 [0.69701627 0.39264347 0.73730444]] 

0.07540738396817304 

0.8524940185694349 



__5. Create a 4x4 matrix of random numbers, subtract 3 from each element.__

In [71]:
matrix1 = np.random.rand(4,4)
matrix2 = matrix1 - 3

print(matrix1, '\n')
print(matrix2)

[[0.9941862  0.80281594 0.54003454 0.08564251]
 [0.90998178 0.47891299 0.48431289 0.70002657]
 [0.29396035 0.87130815 0.65006257 0.41330805]
 [0.70319756 0.73933536 0.82907821 0.23855007]] 

[[-2.0058138  -2.19718406 -2.45996546 -2.91435749]
 [-2.09001822 -2.52108701 -2.51568711 -2.29997343]
 [-2.70603965 -2.12869185 -2.34993743 -2.58669195]
 [-2.29680244 -2.26066464 -2.17092179 -2.76144993]]


__6. Check if two random matrices (3x3) are equal to each other.__

In [79]:
matrix_1 = np.random.rand(3,3)
matrix_2 = np.random.rand(3,3)

matrix_1 == matrix_2 

print(np.allclose(matrix1,matrix2)) #

False


__7. Create a random matrix and swap two columns.__

In [85]:
rand_matrix = np.random.rand(5,3)
print(rand_matrix,'\n')

rand_matrix[:,[0,1]] = rand_matrix[:,[1,0]]

print('\n',rand_matrix) #

[[0.22725842 0.69867966 0.99179672]
 [0.23999749 0.66044529 0.34828988]
 [0.12785848 0.47971136 0.8650692 ]
 [0.71134389 0.90438935 0.48912094]
 [0.11333773 0.06564791 0.99239199]] 


 [[0.69867966 0.22725842 0.99179672]
 [0.66044529 0.23999749 0.34828988]
 [0.47971136 0.12785848 0.8650692 ]
 [0.90438935 0.71134389 0.48912094]
 [0.06564791 0.11333773 0.99239199]]


__8. Create two matrices of size 3x3: one with values from 1 to 9, and the other from 10 to 18. Find the difference and the dot product of these matrices.__

In [73]:
first_matrix = np.arange(1,10).reshape(3,3)
second_matrix = np.arange(10,19).reshape(3,3)

print(first_matrix - second_matrix, '\n')

print(first_matrix * second_matrix)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]] 

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


__9. Create an array of 20 random integers in the range from 10 to 150. Replace all elements less than 30 with -1.__

In [67]:
random_array = np.random.randint(10,151, size = 20)
random_array[random_array < 30] = -1

random_array

array([ 66,  59,  53, 105,  51,  56, 134,  -1,  38,  53, 149, 100,  36,
        57, 130,  63, 141, 148,  54,  -1])