In [1]:
import numpy as np

In [3]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [15]:
first_arr = np.arange(1,11)
filtered_arr = first_arr[first_arr % 2 == 0]
filtered_arr

array([ 2,  4,  6,  8, 10])