In [1]:
import numpy as np

In [45]:
# Task 1.1 ● Создайте два одномерных массива из случайных целых чисел от 1 до 10

arr1 = np.random.randint(1,11,size=(5,2))
arr2 = np.random.randint(1,11,size=(5,2))
print(arr1,'\n')
print(arr2,'\n')

# Task 1.2 ● Выполните поэлементное сложение этих двух массивов.
arr3 = arr1 + arr2
print('2 nd\n',arr3, '\n')

# Task 1.3 ● Измените форму полученного массива на матрицу 2x5.
arr4 = np.reshape(arr3, (2,5))
print('3 th\n',arr4, '\n')

# Task 1.4 ● Посчитайте среднее значение
print('4 th \n',np.mean(arr4))


[[ 9  2]
 [10  4]
 [ 9  3]
 [ 6  2]
 [ 7  3]] 

[[9 3]
 [6 2]
 [9 1]
 [7 5]
 [8 8]] 

2 nd
 [[18  5]
 [16  6]
 [18  4]
 [13  7]
 [15 11]] 

3 th
 [[18  5 16  6 18]
 [ 4 13  7 15 11]] 

4 th 
 11.3


In [75]:
# Task 2.1 ● Создайте массив размером 3x3 и выведите его первую строку и первый столбец.
first_arr = np.arange(1,10).reshape(3,3)
print(first_arr,'\n')
print(first_arr[0:1,:], '\n')
print(first_arr[:,0:1], '\n')

# Task 2.2 ● Измените форму массива с помощью функции reshape и выведите его новую форму.
first_arr = np.reshape(first_arr,(9,1))
print(first_arr, '\n')

# Task 2.3 ● Используйте функцию flatten, чтобы преобразовать массив в одномерный.
print(first_arr.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]] 

[[1]
 [4]
 [7]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 

[1 2 3 4 5 6 7 8 9]


In [133]:
# Task 3.1 ● Создайте двумерный массив размером 4x3 с случайными целыми числами от 1 до 10.
second_arr = np.random.randint(1,11, size=(4,3))
print(second_arr,'\n')

# Task 3.2 ● Объедините столбцы этого массива в один столбец с использованием vstack.
another_arr = np.vstack([second_arr[:, 0:1], second_arr[:, 1:2], second_arr[:, 2:3]])
another_arr

[[ 2  8  5]
 [10 10 10]
 [ 4  8  1]
 [10 10  3]] 



array([[ 2],
       [10],
       [ 4],
       [10],
       [ 8],
       [10],
       [ 8],
       [10],
       [ 5],
       [10],
       [ 1],
       [ 3]])

In [111]:
# Task 4.1 ● Создайте массив из 9 случайных чисел от 1 до 30.

rand_arr = np.random.randint(1,30, size = 9)
print(rand_arr)

# Task 4.2 ● Найдите индекс максимального значения в массиве и выведите это значение.
max_index = np.argmax(rand_arr)

print(f"Maximum number in the array is -> [{rand_arr[max_index]}] and it's index is ->", max_index)


[22 20 27 29 11 26  6  3 27]
Maximum number in the array is -> [29] and it's index is -> 3


In [119]:
# Task 5.1 ● Создайте два массива, каждый размером 2x2, состоящих из случайных целых чисел от 1 до 5.

rand_arr1 = np.random.randint(1,6, size = (2,2))
rand_arr2 = np.random.randint(1,6, size = (2,2))
print('First matrix :\n',rand_arr1, '\n')
print('Second matrix :\n',rand_arr2,'\n')
# Task 5.2 ● Транспонируйте один из массивов.
print('Transposed first array: \n',rand_arr1.T,'\n')


# Task 5.3 ● Сложите транспонированный массив с другим массивом.
print('Sum of two array: \n',rand_arr1 + rand_arr2)

First matrix :
 [[1 1]
 [3 3]] 

Second matrix :
 [[5 1]
 [2 2]] 

Transposed first array: 
 [[1 3]
 [1 3]] 

Sum of two array: 
 [[6 2]
 [5 5]]
